name: HeathRoberson.com
favicon: null
layout_spectrum: 0.25482
typography_spectrum: 1
title: Heath Robertson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#90311e'
    - '#4c4d4f'
    - '#ad695a'
    - '#dab8b1'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
