name: HeathRoberson.com
favicon: null
layout_spectrum: 0.25482
typography_spectrum: 0.25723
title: Heath Robertson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a3820'
    - '#555759'
    - '#993720'
    - '#56585a'
    - '#555555'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.08664557989686728
purpose: []
